name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  list-dockerfiles:
    # list changed or new Dockerfiles and set a matrix with the result
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
        name: checkout with the good fetch-depth
        # purpose of this hack is to work with PR as well as pull
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - id: get-changed-and-new-files
        name: Get changed and new Dockerfiles
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
              echo "changed_dockerfiles=$(git diff --name-only -r HEAD^1 HEAD | grep 'Dockerfile' |xargs)" >> $GITHUB_OUTPUT
            else
              echo "changed_dockerfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Dockerfile' | xargs)" >> $GITHUB_OUTPUT
            fi
      - id: set-matrix
        name: Set matrix
        run: |
          # open bracket \
          echo "matrix=[" >> $GITHUB_OUTPUT \
          for file in ${{ steps.get-changed-and-new-files.outputs.changed_dockerfiles }}; do
            echo "$file has changed or is new" >> $GITHUB_OUTPUT \
            echo "matrix=$matrix, $file" >> $GITHUB_OUTPUT \
          done \
          # close bracket  \
          echo "matrix=$matrix]" >> $GITHUB_OUTPUT \
          echo "computed matrix=$matrix" >> $GITHUB_STEP_SUMMARY
  