name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  list-dockerfiles:
    # list changed or new Dockerfiles and set a matrix with the result
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.output }}

    steps:
      - uses: actions/checkout@v3
        name: checkout with the good fetch-depth
        # purpose of this hack is to work with PR as well as pull
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - id: get-changed-and-new
        name: Get changed and new Dockerfiles
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
              echo "dockerfiles=$(git diff --name-only -r HEAD^1 HEAD | grep 'Dockerfile' |xargs)" >> $GITHUB_ENV
            else
              echo "dockerfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Dockerfile' | xargs)" >> $GITHUB_ENV
            fi
      - id: set-matrix
        name: Set matrix
        run: |
            echo "output=$(echo ${{ steps.get-changed-and-new.dockerfiles }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
      - id: summary
        run: |
          echo "computed matrix=${{ steps.set-matrix.output }}" >> $GITHUB_STEP_SUMMARY

  build-images:
    needs: list-dockerfiles
    if: ${{ needs.list-dockerfiles.outputs.matrix != '' && needs.list-dockerfiles.outputs.matrix != '[""]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        dockerfile: ${{ fromJson(needs.list-dockerfiles.outputs.matrix) }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.dockerfile }}
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}



  