name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  list-dockerfiles:
    # list changed or new Dockerfiles and set a matrix with the result
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
        name: checkout with the good fetch-depth
        # purpose of this hack is to work with PR as well as pull
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - id: get-changed-and-new
        name: Get changed and new Dockerfiles
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
              echo "dockerfiles=$(git diff --name-only -r HEAD^1 HEAD | grep 'Dockerfile' |xargs)" >> $GITHUB_ENV
            else
              echo "dockerfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Dockerfile' | xargs)" >> $GITHUB_ENV
            fi
      - id: set-matrix
        name: Set matrix
        run: |
          if ${{ steps.get-changed-and-new.dockerfiles == ''}}; then 
            echo "matrix=[]" >> $GITHUB_ENV
          else
            echo "matrix=$(echo $steps.get-changed-and-new.dockerfiles | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          fi
      - id: summary
        run: |
          echo "computed matrix=${{ steps.set-matrix.outputs.matrix }}" >> $GITHUB_STEP_SUMMARY
  