name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_dockerfiles=$(git diff --name-only -r HEAD^1 HEAD | grep "Dockerfile" |xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_dockerfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep "Dockerfile" | xargs)" >> $GITHUB_OUTPUT
            fi
      - name: List changed files
        run: |
            for file in ${{ steps.changed-files.outputs.changed_dockerfiles }}; do
                echo "$file was changed"
            done
